<a href="https://colab.research.google.com/github/vvrgit/GenerativeAI/blob/main/Generative_AI_Task1_Error_Computation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
act=np.array([12,20,30,40,50])
pre=np.array([12.5,20.3,30.4,40.6,50.8])

In [19]:
MSE=0
MAE=0
samples=len(act)
for i in range(samples):
  MSE=MSE+(act[i]-pre[i])**2
  MAE=MAE+abs(act[i]-pre[i])
MAE=MAE/samples
MSE=MSE/samples
RMSE=np.sqrt(MSE)
print("Mean Absolte Error", np.round(MAE,2))
print("Mean Square Error", np.round(MSE,2))
print("Root Mean Square Error", np.round(RMSE,2))

Mean Absolte Error 0.52
Mean Square Error 0.3
Root Mean Square Error 0.55


In [25]:
import numpy as np
act=np.array([0,1,2,1,1,2,2])
pre=np.array([0,1,2,0,2,2,1])
res = list(set(act))
values=len(res)
cm=np.zeros([values,values])

In [28]:
for i in range(values):
  for j in range(values):
    if(act[i]==pre[j]):
      cm[act[i],act[i]]=cm[act[i],act[i]]+1


print(cm)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
